# This is my "kladde-område"
# Overview of the work ahead

# Lager en value som har alle navnene som kan velges i Shiny UI
navn <- c("Helsetilstand",
          "Helsetilstand_3mnd",
          "Helsetilstand_12mnd",
          "Helsetilstand_60mnd",
          "SRS22_spm22_3mnd",
          "SRS22_spm22_12mnd",
          "SRS22_spm22_60mnd",
          "SRS22_spm21_3mnd",
          "SRS22_spm21_12mnd",
          "SRS22_spm21_60mnd",
          "BMI_kategori",
          "Alder",
          "Kurve_pre",
          "Kurve_post",
          "Diff_kurve_prosent",
          "Liggetid",
          "Knivtid",
          "Blodtap_100",
          "Blodtap_200",
          "SRS22_total",
          "SRS22_funksjon",
          "SRS22_funksjon_3mnd",
          "SRS22_funksjon_12mnd",
          "SRS22_funksjon_60mnd",
          "SRS22_smerte",
          "SRS22_smerte_3mnd",
          "SRS22_smerte_12mnd",
          "SRS22_smerte_60mnd",
          "SRS22_selvbilde",
          "SRS22_selvbilde_3mnd",
          "SRS22_selvbilde_12mnd",
          "SRS22_selvbilde_60mnd",
          "SRS22_mhelse",
          "SRS22_mhelse_3mnd",
          "SRS22_mhelse_12mnd",
          "SRS22_mhelse_60mnd",
          "SRS22_fornoyd_3mnd",
          "SRS22_fornoyd_12mnd",
          "SRS22_fornoyd_60mnd")



