---
title: 'Startside'
author: 'Ingrid Bondevik'
date: '`r format(Sys.time(), "%d. %B %Y")`'
output: 
  html_document: 
    keep_md: yes
---

# Rapporteket for Deformitet
Velkommen til Rapporteket for Deformitetsregisteret. I rapporteket er det mulig å se figurer og tabeller med oppdaterte data, samt å laste ned og abonnere på rapporter der figurer og tabeller er inkludert.  
Dersom du ikke tilhører registerledelsen vil figurene sammenligne din enhet med resten av landet. Det vil si at det ikke er mulig å se tall for hver enkelt av de andre enhetene.

## Om registeret
Deformitetsregisteret er en del av NKR (Nasjonalt kvalitetsregister for ryggkirurgi). Fra 01.01.23 registreres alle operasjoner for idiopatisk skoliose utført i Norge, uavhengig av pasientens alder. Idiopatisk skoliose er en tilstand som debuterer hos barn og ungdom, og de fleste som opereres gjør dette i tenårene. Kirurgi er omfattende med fare for alvorlige komplikasjoner både på kort og lang sikt. Kirurgi medfører en livsvarig lang avstiving av ryggsøylen med metallimplantater. Det har stor verdi for kvalitetsforbedrende arbeid og forskning at disse pasientene er registrert i et nasjonalt register. Oppfølging med pasientrapporterte data samlet i register er nødvendig for å kunne oppdage endring i livskvalitet og eventuelle komplikasjoner på lang sikt. 
I Norge behandles idiopatisk skoliose ved Haukeland Universitetssjukehus, St.Olavs hospital og Rikshospitalet-OUS. Alle 3 sykehus rapporterer sine operasjoner til registeret. 

Ved inkludering i registeret fyller pasienten ut samtykke og preoperativt skjema. Kirurg fyller ut legeskjema etter operasjon. Pasienter fyller ut skjema postoperativt etter 6 måneder, 2år og 5 år. Dette blir tilsendt og fylles ut elektronisk.
Alle reoperasjoner skal registreres. Dersom pasienter med skoliose opereres for en annen degenerativ rygglidelse (spinal stenose, prolaps etc.) registreres dette i NKR degenerativ, ikke i Deformitet.
